//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyVersion("1.0.*")]
[assembly: AssemblyInformationalVersion("1.0.develop-86f4741a")]

namespace SM2
{
    internal class BuildInfo
    {
        public const string CompileSHA = "86f4741a";
        public const string CompileBranch = "develop";
        #if DEBUG
        public const string CompileMode = "Debug";
        #else
        public const string CompileMode = "Release";
        #endif
    }
}
